package types

import (
	"fmt"
	"log"
	"mapreduce/pkg/utils"
	"os"
	"strconv"
	"strings"
	"unicode"
)

// Load the application Map and Reduce functions
func LoadApp(appname string) (func(string, string) utils.ByKey, func(string, []string) string) {
	var mapf func(string, string) utils.ByKey
	var reducef func(string, []string) string
	if appname == "wordcount" || appname == "wc" {
		fmt.Println("Executing wordcount..")
		mapf = WcMap
		reducef = WcReduce
	} else if appname == "checkhealth" || appname == "ch" {
		fmt.Println("Executing checkhealth..")
		CallCheckHealth()
		os.Exit(0)
	} else {
		log.Fatalf("Unsupported application.")
	}

	return mapf, reducef
}

// The map function is called once for each file of input. The first
// argument is the name of the input file, and the second is the
// file's complete contents. It ignores the input file name,
// and look only at the contents argument. The return value is a slice
// of key/value pairs.
// TODO: Make MR applications plugins
func WcMap(filename string, contents string) utils.ByKey {
	// function to detect word separators.
	ff := func(r rune) bool { return !unicode.IsLetter(r) }

	// split contents into an array of words.
	words := strings.FieldsFunc(contents, ff)

	kva := []utils.KeyValue{}
	for _, w := range words {
		kv := utils.KeyValue{Key: strings.ToLower(w), Value: "1"}
		kva = append(kva, kv)
	}
	return kva
}

// The reduce function is called once for each key generated by the
// map tasks, with a list of all the values created for that key by
// any map task.
func WcReduce(key string, values []string) string {
	// return the number of occurrences of this word.
	return strconv.Itoa(len(values))
}
